#!/usr/bin/env tsx
/**
 * Seed data generator for DDD Tool demos.
 *
 * Reads all files from a DDD project directory and outputs a TypeScript
 * seed file that can be loaded into the VFS at runtime.
 *
 * Usage:
 *   tsx demo/scripts/generate-seed.ts ~/dev/vantage-test/
 *   → writes demo/data/vantage-project.ts
 */

import * as fs from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// ---------------------------------------------------------------------------
// CLI args
// ---------------------------------------------------------------------------

const projectDir = process.argv[2];
if (!projectDir) {
  console.error('Usage: tsx demo/scripts/generate-seed.ts <project-dir>');
  process.exit(1);
}

const resolvedDir = path.resolve(projectDir);
if (!fs.existsSync(resolvedDir)) {
  console.error(`Directory not found: ${resolvedDir}`);
  process.exit(1);
}

const projectJsonPath = path.join(resolvedDir, 'ddd-project.json');
if (!fs.existsSync(projectJsonPath)) {
  console.error(`Not a DDD project (missing ddd-project.json): ${resolvedDir}`);
  process.exit(1);
}

// ---------------------------------------------------------------------------
// Read project
// ---------------------------------------------------------------------------

const projectJson = JSON.parse(fs.readFileSync(projectJsonPath, 'utf-8'));
const projectName: string = projectJson.name || path.basename(resolvedDir);

console.log(`Reading project: ${projectName} from ${resolvedDir}`);

// Collect all files: ddd-project.json + specs/**/*.yaml
const files: Array<{ relativePath: string; content: string }> = [];

// ddd-project.json
files.push({
  relativePath: 'ddd-project.json',
  content: fs.readFileSync(projectJsonPath, 'utf-8'),
});

// Recursively collect YAML files under specs/
function collectYaml(dir: string, prefix: string) {
  const entries = fs.readdirSync(dir, { withFileTypes: true });
  for (const entry of entries) {
    const fullPath = path.join(dir, entry.name);
    const relPath = prefix ? `${prefix}/${entry.name}` : entry.name;
    if (entry.isDirectory()) {
      collectYaml(fullPath, relPath);
    } else if (entry.name.endsWith('.yaml') || entry.name.endsWith('.yml')) {
      files.push({
        relativePath: `specs/${relPath}`,
        content: fs.readFileSync(fullPath, 'utf-8'),
      });
    }
  }
}

const specsDir = path.join(resolvedDir, 'specs');
if (fs.existsSync(specsDir)) {
  collectYaml(specsDir, '');
}

console.log(`  Found ${files.length} files (1 JSON + ${files.length - 1} YAML)`);

// ---------------------------------------------------------------------------
// Count stats for header comment
// ---------------------------------------------------------------------------

const domainCount = projectJson.domains?.length ?? 0;
let flowCount = 0;
const nodeTypes = new Set<string>();

for (const f of files) {
  if (f.relativePath.includes('/flows/') && f.relativePath.endsWith('.yaml')) {
    flowCount++;
    // Quick scan for node types
    const typeMatches = f.content.matchAll(/^\s+type:\s+(\w+)/gm);
    for (const m of typeMatches) {
      if (m[1] !== 'traditional' && m[1] !== 'agent') {
        nodeTypes.add(m[1]);
      }
    }
  }
}

// ---------------------------------------------------------------------------
// Generate TypeScript output
// ---------------------------------------------------------------------------

const vfsBase = `/demo/${projectName}`;
const demoHome = '/demo';

let output = `/**
 * Static ${projectName} project data for demo mode.
 * Auto-generated by: tsx demo/scripts/generate-seed.ts <project-dir>
 *
 * Project: ${projectJson.description || projectName}
 * ${domainCount} domains, ${flowCount} flows, ${nodeTypes.size} node types
 * ${files.length} files (${files.filter(f => f.relativePath.endsWith('.yaml')).length} YAML + 1 JSON)
 *
 * DO NOT EDIT — regenerate with the command above.
 */

export const DEMO_HOME = '${demoHome}';
export const DEMO_PROJECT_PATH = '${vfsBase}';

export const SEED_FILES: Record<string, string> = {};

// --- Settings & recent projects ---
SEED_FILES[\`\${DEMO_HOME}/.ddd-tool/settings.json\`] = ${JSON.stringify(JSON.stringify({
  claudeCode: { enabled: true, command: 'claude' },
  editor: {
    gridSnap: true,
    autoSave: false,
    autoSaveInterval: 30,
    theme: 'dark',
    fontSize: 14,
    saveNotification: true,
  },
  git: {
    autoCommitMessage: 'DDD: {action} in {flow_id}',
    branchNaming: 'ddd/{flow_id}',
  },
}, null, 2))};

SEED_FILES[\`\${DEMO_HOME}/.ddd-tool/recent-projects.json\`] = ${JSON.stringify(JSON.stringify([{
  name: projectName,
  path: vfsBase,
  lastOpenedAt: new Date().toISOString(),
  description: projectJson.description || '',
}], null, 2))};

// --- Project files ---
`;

for (const f of files) {
  const vfsPath = `\${DEMO_PROJECT_PATH}/${f.relativePath}`;
  // Use template literal with backtick-safe escaping
  const escaped = f.content
    .replace(/\\/g, '\\\\')
    .replace(/`/g, '\\`')
    .replace(/\$/g, '\\$');
  output += `SEED_FILES[\`${vfsPath}\`] = \`${escaped}\`;\n\n`;
}

// ---------------------------------------------------------------------------
// Write output
// ---------------------------------------------------------------------------

const outputPath = path.join(__dirname, '..', 'data', `${projectName}-project.ts`);
fs.mkdirSync(path.dirname(outputPath), { recursive: true });
fs.writeFileSync(outputPath, output, 'utf-8');

console.log(`  Generated: ${path.relative(process.cwd(), outputPath)}`);
console.log(`  VFS root: ${vfsBase}`);
console.log(`  Stats: ${domainCount} domains, ${flowCount} flows, ${nodeTypes.size} node types`);
console.log('Done.');
