import type { DomainConfig } from '../types/domain';

export function generateClaudeMd(
  domainConfigs: Record<string, DomainConfig>,
  existingContent?: string
): string {
  const lines: string[] = [];

  lines.push('# Project Context (Auto-generated by DDD Tool)');
  lines.push('');

  // Domain table
  lines.push('## Domains');
  lines.push('');
  lines.push('| Domain | Role | Schemas | Flows | Description |');
  lines.push('|--------|------|---------|-------|-------------|');

  for (const [id, config] of Object.entries(domainConfigs)) {
    const role = config.role ?? '—';
    const schemas = Array.isArray(config.owns_schemas) && config.owns_schemas.length > 0
      ? config.owns_schemas.join(', ')
      : '—';
    const flowCount = config.flows.length;
    const desc = config.description ?? '—';
    lines.push(`| ${config.name} (${id}) | ${role} | ${schemas} | ${flowCount} | ${desc} |`);
  }

  lines.push('');

  // Flows per domain
  lines.push('## Flows');
  lines.push('');

  for (const [id, config] of Object.entries(domainConfigs)) {
    if (config.flows.length === 0) continue;
    lines.push(`### ${config.name} (${id})`);
    lines.push('');
    for (const flow of config.flows) {
      const typeTag = flow.type === 'agent' ? ' [agent]' : '';
      const desc = flow.description ? ` — ${flow.description}` : '';
      lines.push(`- **${flow.name}** (\`${flow.id}\`)${typeTag}${desc}`);
    }
    lines.push('');
  }

  // Event wiring summary
  const hasEvents = Object.values(domainConfigs).some(
    (c) => c.publishes_events.length > 0 || c.consumes_events.length > 0
  );

  if (hasEvents) {
    lines.push('## Event Wiring');
    lines.push('');

    for (const [id, config] of Object.entries(domainConfigs)) {
      const pub = config.publishes_events;
      const con = config.consumes_events;
      if (pub.length === 0 && con.length === 0) continue;

      lines.push(`### ${config.name} (${id})`);
      if (pub.length > 0) {
        lines.push('**Publishes:**');
        for (const e of pub) {
          const from = e.from_flow ? ` (from ${e.from_flow})` : '';
          lines.push(`- \`${e.event}\`${from}`);
        }
      }
      if (con.length > 0) {
        lines.push('**Consumes:**');
        for (const e of con) {
          const handler = e.handled_by_flow ? ` (handled by ${e.handled_by_flow})` : '';
          lines.push(`- \`${e.event}\`${handler}`);
        }
      }
      lines.push('');
    }
  }

  // Preserve custom section from existing CLAUDE.md
  let customSection = '';
  if (existingContent) {
    const customMarker = '<!-- CUSTOM -->';
    const customIdx = existingContent.indexOf(customMarker);
    if (customIdx !== -1) {
      customSection = existingContent.slice(customIdx);
    }
  }

  if (customSection) {
    lines.push(customSection);
  } else {
    lines.push('<!-- CUSTOM -->');
    lines.push('<!-- Add your custom project notes below this line. They will be preserved on regeneration. -->');
    lines.push('');
  }

  return lines.join('\n');
}
